/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UpgradeRouteImport } from './routes/upgrade'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as IndexRouteImport } from './routes/index'
import { Route as UpgradeIndexRouteImport } from './routes/upgrade/index'
import { Route as DashboardIndexRouteImport } from './routes/dashboard/index'
import { Route as UpgradeSuccessRouteImport } from './routes/upgrade/success'
import { Route as InviteSlugRouteImport } from './routes/invite/$slug'
import { Route as EditorNewRouteImport } from './routes/editor/new'
import { Route as EditorInvitationIdRouteImport } from './routes/editor/$invitationId'
import { Route as AuthSignupRouteImport } from './routes/auth/signup'
import { Route as AuthResetRouteImport } from './routes/auth/reset'
import { Route as AuthLoginRouteImport } from './routes/auth/login'
import { Route as AuthCallbackRouteImport } from './routes/auth/callback'
import { Route as DashboardInvitationIdIndexRouteImport } from './routes/dashboard/$invitationId/index'

const UpgradeRoute = UpgradeRouteImport.update({
  id: '/upgrade',
  path: '/upgrade',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const UpgradeIndexRoute = UpgradeIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => UpgradeRoute,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/dashboard/',
  path: '/dashboard/',
  getParentRoute: () => rootRouteImport,
} as any)
const UpgradeSuccessRoute = UpgradeSuccessRouteImport.update({
  id: '/success',
  path: '/success',
  getParentRoute: () => UpgradeRoute,
} as any)
const InviteSlugRoute = InviteSlugRouteImport.update({
  id: '/invite/$slug',
  path: '/invite/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const EditorNewRoute = EditorNewRouteImport.update({
  id: '/editor/new',
  path: '/editor/new',
  getParentRoute: () => rootRouteImport,
} as any)
const EditorInvitationIdRoute = EditorInvitationIdRouteImport.update({
  id: '/editor/$invitationId',
  path: '/editor/$invitationId',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthSignupRoute = AuthSignupRouteImport.update({
  id: '/auth/signup',
  path: '/auth/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthResetRoute = AuthResetRouteImport.update({
  id: '/auth/reset',
  path: '/auth/reset',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/auth/login',
  path: '/auth/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthCallbackRoute = AuthCallbackRouteImport.update({
  id: '/auth/callback',
  path: '/auth/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardInvitationIdIndexRoute =
  DashboardInvitationIdIndexRouteImport.update({
    id: '/dashboard/$invitationId/',
    path: '/dashboard/$invitationId/',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/privacy': typeof PrivacyRoute
  '/terms': typeof TermsRoute
  '/upgrade': typeof UpgradeRouteWithChildren
  '/auth/callback': typeof AuthCallbackRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/reset': typeof AuthResetRoute
  '/auth/signup': typeof AuthSignupRoute
  '/editor/$invitationId': typeof EditorInvitationIdRoute
  '/editor/new': typeof EditorNewRoute
  '/invite/$slug': typeof InviteSlugRoute
  '/upgrade/success': typeof UpgradeSuccessRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/upgrade/': typeof UpgradeIndexRoute
  '/dashboard/$invitationId/': typeof DashboardInvitationIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/privacy': typeof PrivacyRoute
  '/terms': typeof TermsRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/reset': typeof AuthResetRoute
  '/auth/signup': typeof AuthSignupRoute
  '/editor/$invitationId': typeof EditorInvitationIdRoute
  '/editor/new': typeof EditorNewRoute
  '/invite/$slug': typeof InviteSlugRoute
  '/upgrade/success': typeof UpgradeSuccessRoute
  '/dashboard': typeof DashboardIndexRoute
  '/upgrade': typeof UpgradeIndexRoute
  '/dashboard/$invitationId': typeof DashboardInvitationIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/privacy': typeof PrivacyRoute
  '/terms': typeof TermsRoute
  '/upgrade': typeof UpgradeRouteWithChildren
  '/auth/callback': typeof AuthCallbackRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/reset': typeof AuthResetRoute
  '/auth/signup': typeof AuthSignupRoute
  '/editor/$invitationId': typeof EditorInvitationIdRoute
  '/editor/new': typeof EditorNewRoute
  '/invite/$slug': typeof InviteSlugRoute
  '/upgrade/success': typeof UpgradeSuccessRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/upgrade/': typeof UpgradeIndexRoute
  '/dashboard/$invitationId/': typeof DashboardInvitationIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/privacy'
    | '/terms'
    | '/upgrade'
    | '/auth/callback'
    | '/auth/login'
    | '/auth/reset'
    | '/auth/signup'
    | '/editor/$invitationId'
    | '/editor/new'
    | '/invite/$slug'
    | '/upgrade/success'
    | '/dashboard/'
    | '/upgrade/'
    | '/dashboard/$invitationId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/privacy'
    | '/terms'
    | '/auth/callback'
    | '/auth/login'
    | '/auth/reset'
    | '/auth/signup'
    | '/editor/$invitationId'
    | '/editor/new'
    | '/invite/$slug'
    | '/upgrade/success'
    | '/dashboard'
    | '/upgrade'
    | '/dashboard/$invitationId'
  id:
    | '__root__'
    | '/'
    | '/privacy'
    | '/terms'
    | '/upgrade'
    | '/auth/callback'
    | '/auth/login'
    | '/auth/reset'
    | '/auth/signup'
    | '/editor/$invitationId'
    | '/editor/new'
    | '/invite/$slug'
    | '/upgrade/success'
    | '/dashboard/'
    | '/upgrade/'
    | '/dashboard/$invitationId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  PrivacyRoute: typeof PrivacyRoute
  TermsRoute: typeof TermsRoute
  UpgradeRoute: typeof UpgradeRouteWithChildren
  AuthCallbackRoute: typeof AuthCallbackRoute
  AuthLoginRoute: typeof AuthLoginRoute
  AuthResetRoute: typeof AuthResetRoute
  AuthSignupRoute: typeof AuthSignupRoute
  EditorInvitationIdRoute: typeof EditorInvitationIdRoute
  EditorNewRoute: typeof EditorNewRoute
  InviteSlugRoute: typeof InviteSlugRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
  DashboardInvitationIdIndexRoute: typeof DashboardInvitationIdIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/upgrade': {
      id: '/upgrade'
      path: '/upgrade'
      fullPath: '/upgrade'
      preLoaderRoute: typeof UpgradeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/upgrade/': {
      id: '/upgrade/'
      path: '/'
      fullPath: '/upgrade/'
      preLoaderRoute: typeof UpgradeIndexRouteImport
      parentRoute: typeof UpgradeRoute
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/dashboard'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/upgrade/success': {
      id: '/upgrade/success'
      path: '/success'
      fullPath: '/upgrade/success'
      preLoaderRoute: typeof UpgradeSuccessRouteImport
      parentRoute: typeof UpgradeRoute
    }
    '/invite/$slug': {
      id: '/invite/$slug'
      path: '/invite/$slug'
      fullPath: '/invite/$slug'
      preLoaderRoute: typeof InviteSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/editor/new': {
      id: '/editor/new'
      path: '/editor/new'
      fullPath: '/editor/new'
      preLoaderRoute: typeof EditorNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/editor/$invitationId': {
      id: '/editor/$invitationId'
      path: '/editor/$invitationId'
      fullPath: '/editor/$invitationId'
      preLoaderRoute: typeof EditorInvitationIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/signup': {
      id: '/auth/signup'
      path: '/auth/signup'
      fullPath: '/auth/signup'
      preLoaderRoute: typeof AuthSignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/reset': {
      id: '/auth/reset'
      path: '/auth/reset'
      fullPath: '/auth/reset'
      preLoaderRoute: typeof AuthResetRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/login': {
      id: '/auth/login'
      path: '/auth/login'
      fullPath: '/auth/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/callback': {
      id: '/auth/callback'
      path: '/auth/callback'
      fullPath: '/auth/callback'
      preLoaderRoute: typeof AuthCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/$invitationId/': {
      id: '/dashboard/$invitationId/'
      path: '/dashboard/$invitationId'
      fullPath: '/dashboard/$invitationId/'
      preLoaderRoute: typeof DashboardInvitationIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface UpgradeRouteChildren {
  UpgradeSuccessRoute: typeof UpgradeSuccessRoute
  UpgradeIndexRoute: typeof UpgradeIndexRoute
}

const UpgradeRouteChildren: UpgradeRouteChildren = {
  UpgradeSuccessRoute: UpgradeSuccessRoute,
  UpgradeIndexRoute: UpgradeIndexRoute,
}

const UpgradeRouteWithChildren =
  UpgradeRoute._addFileChildren(UpgradeRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  PrivacyRoute: PrivacyRoute,
  TermsRoute: TermsRoute,
  UpgradeRoute: UpgradeRouteWithChildren,
  AuthCallbackRoute: AuthCallbackRoute,
  AuthLoginRoute: AuthLoginRoute,
  AuthResetRoute: AuthResetRoute,
  AuthSignupRoute: AuthSignupRoute,
  EditorInvitationIdRoute: EditorInvitationIdRoute,
  EditorNewRoute: EditorNewRoute,
  InviteSlugRoute: InviteSlugRoute,
  DashboardIndexRoute: DashboardIndexRoute,
  DashboardInvitationIdIndexRoute: DashboardInvitationIdIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
